Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,10 +20,15 @@ jobs:
     - name: Generate CycloneDX SBOM with vulnerabilities
       run: |
         mkdir -p sbom-results
-        trivy fs ./cyclonedx-sbom-cb --scanners vuln,secret --format cyclonedx --output sbom-results/sbom.json || true
+        trivy fs . --scanners vuln,secret --format cyclonedx --output sbom-results/sbom.json || true
 
     - name: Send SBOM to Challenge Listener
       run: |
+        if [ -f sbom-results/sbom.json ]; then
         curl -X POST -H "Content-Type: application/json" \
         --data @sbom-results/sbom.json \
-        http://35.219.182.3:8880/callback
+        http://35.219.169.50:8880/callback
+        else
+        echo "SBOM file not found. Skipping callback."
+        exit 1
+        fi
